package model;
// Generated Dec 29, 2011 5:10:49 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Product generated by hbm2java
 */
public class Product  implements java.io.Serializable {


     private Long productId;
     private User user;
     private String name;
     private double vat;
     private BigDecimal price;
     private BigDecimal postage;
     private String delivaryTime;
     private String description;
     private long unitsSold;
     private long qty;
     private Integer fflag;
     private String status;
     private Date date;
     private Set<Order> orders = new HashSet<Order>(0);
     private Set<Product> productsForRelatedId = new HashSet<Product>(0);
     private Set<Productvariant> productvariants = new HashSet<Productvariant>(0);
     private Set<Productimage> productimages = new HashSet<Productimage>(0);
     private Set<Product> productsForProductId = new HashSet<Product>(0);
     private Set<Temporder> temporders = new HashSet<Temporder>(0);
     private Set<Stalldisplay> stalldisplaies = new HashSet<Stalldisplay>(0);

    public Product() {
    }

	
    public Product(User user, String name, double vat, BigDecimal price, BigDecimal postage, String delivaryTime, long unitsSold, long qty, Date date) {
        this.user = user;
        this.name = name;
        this.vat = vat;
        this.price = price;
        this.postage = postage;
        this.delivaryTime = delivaryTime;
        this.unitsSold = unitsSold;
        this.qty = qty;
        this.date = date;
    }
    public Product(User user, String name, double vat, BigDecimal price, BigDecimal postage, String delivaryTime, String description, long unitsSold, long qty, Integer fflag, String status, Date date, Set<Order> orders, Set<Product> productsForRelatedId, Set<Productvariant> productvariants, Set<Productimage> productimages, Set<Product> productsForProductId, Set<Temporder> temporders, Set<Stalldisplay> stalldisplaies) {
       this.user = user;
       this.name = name;
       this.vat = vat;
       this.price = price;
       this.postage = postage;
       this.delivaryTime = delivaryTime;
       this.description = description;
       this.unitsSold = unitsSold;
       this.qty = qty;
       this.fflag = fflag;
       this.status = status;
       this.date = date;
       this.orders = orders;
       this.productsForRelatedId = productsForRelatedId;
       this.productvariants = productvariants;
       this.productimages = productimages;
       this.productsForProductId = productsForProductId;
       this.temporders = temporders;
       this.stalldisplaies = stalldisplaies;
    }
   
    public Long getProductId() {
        return this.productId;
    }
    
    public void setProductId(Long productId) {
        this.productId = productId;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public double getVat() {
        return this.vat;
    }
    
    public void setVat(double vat) {
        this.vat = vat;
    }
    public BigDecimal getPrice() {
        return this.price;
    }
    
    public void setPrice(BigDecimal price) {
        this.price = price;
    }
    public BigDecimal getPostage() {
        return this.postage;
    }
    
    public void setPostage(BigDecimal postage) {
        this.postage = postage;
    }
    public String getDelivaryTime() {
        return this.delivaryTime;
    }
    
    public void setDelivaryTime(String delivaryTime) {
        this.delivaryTime = delivaryTime;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public long getUnitsSold() {
        return this.unitsSold;
    }
    
    public void setUnitsSold(long unitsSold) {
        this.unitsSold = unitsSold;
    }
    public long getQty() {
        return this.qty;
    }
    
    public void setQty(long qty) {
        this.qty = qty;
    }
    public Integer getFflag() {
        return this.fflag;
    }
    
    public void setFflag(Integer fflag) {
        this.fflag = fflag;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public Set<Order> getOrders() {
        return this.orders;
    }
    
    public void setOrders(Set<Order> orders) {
        this.orders = orders;
    }
    public Set<Product> getProductsForRelatedId() {
        return this.productsForRelatedId;
    }
    
    public void setProductsForRelatedId(Set<Product> productsForRelatedId) {
        this.productsForRelatedId = productsForRelatedId;
    }
    public Set<Productvariant> getProductvariants() {
        return this.productvariants;
    }
    
    public void setProductvariants(Set<Productvariant> productvariants) {
        this.productvariants = productvariants;
    }
    public Set<Productimage> getProductimages() {
        return this.productimages;
    }
    
    public void setProductimages(Set<Productimage> productimages) {
        this.productimages = productimages;
    }
    public Set<Product> getProductsForProductId() {
        return this.productsForProductId;
    }
    
    public void setProductsForProductId(Set<Product> productsForProductId) {
        this.productsForProductId = productsForProductId;
    }
    public Set<Temporder> getTemporders() {
        return this.temporders;
    }
    
    public void setTemporders(Set<Temporder> temporders) {
        this.temporders = temporders;
    }
    public Set<Stalldisplay> getStalldisplaies() {
        return this.stalldisplaies;
    }
    
    public void setStalldisplaies(Set<Stalldisplay> stalldisplaies) {
        this.stalldisplaies = stalldisplaies;
    }




}


