package model;
// Generated Dec 29, 2011 5:10:49 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * Productvariant generated by hbm2java
 */
public class Productvariant  implements java.io.Serializable {


     private Long variantsId;
     private Product product;
     private int unitsSold;
     private BigDecimal price;
     private int qty;
     private String desc;

    public Productvariant() {
    }

    public Productvariant(Product product, int unitsSold, BigDecimal price, int qty, String desc) {
       this.product = product;
       this.unitsSold = unitsSold;
       this.price = price;
       this.qty = qty;
       this.desc = desc;
    }
   
    public Long getVariantsId() {
        return this.variantsId;
    }
    
    public void setVariantsId(Long variantsId) {
        this.variantsId = variantsId;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public int getUnitsSold() {
        return this.unitsSold;
    }
    
    public void setUnitsSold(int unitsSold) {
        this.unitsSold = unitsSold;
    }
    public BigDecimal getPrice() {
        return this.price;
    }
    
    public void setPrice(BigDecimal price) {
        this.price = price;
    }
    public int getQty() {
        return this.qty;
    }
    
    public void setQty(int qty) {
        this.qty = qty;
    }
    public String getDesc() {
        return this.desc;
    }
    
    public void setDesc(String desc) {
        this.desc = desc;
    }




}


