package model;
// Generated Dec 29, 2011 5:10:49 PM by Hibernate Tools 3.2.1.GA



/**
 * Productimage generated by hbm2java
 */
public class Productimage  implements java.io.Serializable {


     private long prodId;
     private Product product;
     private byte[] imagefile;
     private byte[] img2;
     private byte[] img3;

    public Productimage() {
    }

	
    public Productimage(long prodId, Product product) {
        this.prodId = prodId;
        this.product = product;
    }
    public Productimage(long prodId, Product product, byte[] imagefile, byte[] img2, byte[] img3) {
       this.prodId = prodId;
       this.product = product;
       this.imagefile = imagefile;
       this.img2 = img2;
       this.img3 = img3;
    }
   
    public long getProdId() {
        return this.prodId;
    }
    
    public void setProdId(long prodId) {
        this.prodId = prodId;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public byte[] getImagefile() {
        return this.imagefile;
    }
    
    public void setImagefile(byte[] imagefile) {
        this.imagefile = imagefile;
    }
    public byte[] getImg2() {
        return this.img2;
    }
    
    public void setImg2(byte[] img2) {
        this.img2 = img2;
    }
    public byte[] getImg3() {
        return this.img3;
    }
    
    public void setImg3(byte[] img3) {
        this.img3 = img3;
    }




}


