package model;
// Generated Dec 29, 2011 5:10:49 PM by Hibernate Tools 3.2.1.GA



/**
 * Showimage generated by hbm2java
 */
public class Showimage  implements java.io.Serializable {


     private int showId;
     private Show show;
     private byte[] logo;
     private byte[] showLayout;
     private byte[] showImage;

    public Showimage() {
    }

	
    public Showimage(int showId, Show show) {
        this.showId = showId;
        this.show = show;
    }
    public Showimage(int showId, Show show, byte[] logo, byte[] showLayout, byte[] showImage) {
       this.showId = showId;
       this.show = show;
       this.logo = logo;
       this.showLayout = showLayout;
       this.showImage = showImage;
    }
   
    public int getShowId() {
        return this.showId;
    }
    
    public void setShowId(int showId) {
        this.showId = showId;
    }
    public Show getShow() {
        return this.show;
    }
    
    public void setShow(Show show) {
        this.show = show;
    }
    public byte[] getLogo() {
        return this.logo;
    }
    
    public void setLogo(byte[] logo) {
        this.logo = logo;
    }
    public byte[] getShowLayout() {
        return this.showLayout;
    }
    
    public void setShowLayout(byte[] showLayout) {
        this.showLayout = showLayout;
    }
    public byte[] getShowImage() {
        return this.showImage;
    }
    
    public void setShowImage(byte[] showImage) {
        this.showImage = showImage;
    }




}


