package model;
// Generated Dec 29, 2011 5:10:49 PM by Hibernate Tools 3.2.1.GA



/**
 * Showdisplay generated by hbm2java
 */
public class Showdisplay  implements java.io.Serializable {


     private Long layoutid;
     private Show show;
     private Stall stall;
     private int x1;
     private int x2;
     private int y1;
     private int y2;

    public Showdisplay() {
    }

    public Showdisplay(Show show, Stall stall, int x1, int x2, int y1, int y2) {
       this.show = show;
       this.stall = stall;
       this.x1 = x1;
       this.x2 = x2;
       this.y1 = y1;
       this.y2 = y2;
    }
   
    public Long getLayoutid() {
        return this.layoutid;
    }
    
    public void setLayoutid(Long layoutid) {
        this.layoutid = layoutid;
    }
    public Show getShow() {
        return this.show;
    }
    
    public void setShow(Show show) {
        this.show = show;
    }
    public Stall getStall() {
        return this.stall;
    }
    
    public void setStall(Stall stall) {
        this.stall = stall;
    }
    public int getX1() {
        return this.x1;
    }
    
    public void setX1(int x1) {
        this.x1 = x1;
    }
    public int getX2() {
        return this.x2;
    }
    
    public void setX2(int x2) {
        this.x2 = x2;
    }
    public int getY1() {
        return this.y1;
    }
    
    public void setY1(int y1) {
        this.y1 = y1;
    }
    public int getY2() {
        return this.y2;
    }
    
    public void setY2(int y2) {
        this.y2 = y2;
    }




}


