package model;
// Generated Dec 29, 2011 5:10:49 PM by Hibernate Tools 3.2.1.GA



/**
 * Stalldisplay generated by hbm2java
 */
public class Stalldisplay  implements java.io.Serializable {


     private Long displayId;
     private Stall stall;
     private Product product;
     private int x1;
     private int x2;
     private int y1;
     private int y2;

    public Stalldisplay() {
    }

    public Stalldisplay(Stall stall, Product product, int x1, int x2, int y1, int y2) {
       this.stall = stall;
       this.product = product;
       this.x1 = x1;
       this.x2 = x2;
       this.y1 = y1;
       this.y2 = y2;
    }
   
    public Long getDisplayId() {
        return this.displayId;
    }
    
    public void setDisplayId(Long displayId) {
        this.displayId = displayId;
    }
    public Stall getStall() {
        return this.stall;
    }
    
    public void setStall(Stall stall) {
        this.stall = stall;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public int getX1() {
        return this.x1;
    }
    
    public void setX1(int x1) {
        this.x1 = x1;
    }
    public int getX2() {
        return this.x2;
    }
    
    public void setX2(int x2) {
        this.x2 = x2;
    }
    public int getY1() {
        return this.y1;
    }
    
    public void setY1(int y1) {
        this.y1 = y1;
    }
    public int getY2() {
        return this.y2;
    }
    
    public void setY2(int y2) {
        this.y2 = y2;
    }




}


