package model;
// Generated Dec 29, 2011 5:10:49 PM by Hibernate Tools 3.2.1.GA



/**
 * UserAddress generated by hbm2java
 */
public class UserAddress  implements java.io.Serializable {


     private String user;
     private User user_1;
     private String addressline1;
     private String addressline2;
     private String city;
     private String country;
     private String postcode;

    public UserAddress() {
    }

	
    public UserAddress(String user, User user_1) {
        this.user = user;
        this.user_1 = user_1;
    }
    public UserAddress(String user, User user_1, String addressline1, String addressline2, String city, String country, String postcode) {
       this.user = user;
       this.user_1 = user_1;
       this.addressline1 = addressline1;
       this.addressline2 = addressline2;
       this.city = city;
       this.country = country;
       this.postcode = postcode;
    }
   
    public String getUser() {
        return this.user;
    }
    
    public void setUser(String user) {
        this.user = user;
    }
    public User getUser_1() {
        return this.user_1;
    }
    
    public void setUser_1(User user_1) {
        this.user_1 = user_1;
    }
    public String getAddressline1() {
        return this.addressline1;
    }
    
    public void setAddressline1(String addressline1) {
        this.addressline1 = addressline1;
    }
    public String getAddressline2() {
        return this.addressline2;
    }
    
    public void setAddressline2(String addressline2) {
        this.addressline2 = addressline2;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }
    public String getPostcode() {
        return this.postcode;
    }
    
    public void setPostcode(String postcode) {
        this.postcode = postcode;
    }




}


