package model;
// Generated Dec 29, 2011 5:10:49 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private String user;
     private User user_1;
     private String company;
     private String vatregister;
     private String vatno;
     private String firstname;
     private String lastname;
     private String memorableWord;
     private String webLink;
     private String duedate;
     private Long phone;
     private Long mobile;
     private String bankname;
     private Integer accountNo;
     private String branchCode;
     private String accholderName;
     private Integer approve;
     private BigDecimal balance;
     private String note;
     private String info;

    public Users() {
    }

	
    public Users(String user, User user_1) {
        this.user = user;
        this.user_1 = user_1;
    }
    public Users(String user, User user_1, String company, String vatregister, String vatno, String firstname, String lastname, String memorableWord, String webLink, String duedate, Long phone, Long mobile, String bankname, Integer accountNo, String branchCode, String accholderName, Integer approve, BigDecimal balance, String note, String info) {
       this.user = user;
       this.user_1 = user_1;
       this.company = company;
       this.vatregister = vatregister;
       this.vatno = vatno;
       this.firstname = firstname;
       this.lastname = lastname;
       this.memorableWord = memorableWord;
       this.webLink = webLink;
       this.duedate = duedate;
       this.phone = phone;
       this.mobile = mobile;
       this.bankname = bankname;
       this.accountNo = accountNo;
       this.branchCode = branchCode;
       this.accholderName = accholderName;
       this.approve = approve;
       this.balance = balance;
       this.note = note;
       this.info = info;
    }
   
    public String getUser() {
        return this.user;
    }
    
    public void setUser(String user) {
        this.user = user;
    }
    public User getUser_1() {
        return this.user_1;
    }
    
    public void setUser_1(User user_1) {
        this.user_1 = user_1;
    }
    public String getCompany() {
        return this.company;
    }
    
    public void setCompany(String company) {
        this.company = company;
    }
    public String getVatregister() {
        return this.vatregister;
    }
    
    public void setVatregister(String vatregister) {
        this.vatregister = vatregister;
    }
    public String getVatno() {
        return this.vatno;
    }
    
    public void setVatno(String vatno) {
        this.vatno = vatno;
    }
    public String getFirstname() {
        return this.firstname;
    }
    
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }
    public String getLastname() {
        return this.lastname;
    }
    
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }
    public String getMemorableWord() {
        return this.memorableWord;
    }
    
    public void setMemorableWord(String memorableWord) {
        this.memorableWord = memorableWord;
    }
    public String getWebLink() {
        return this.webLink;
    }
    
    public void setWebLink(String webLink) {
        this.webLink = webLink;
    }
    public String getDuedate() {
        return this.duedate;
    }
    
    public void setDuedate(String duedate) {
        this.duedate = duedate;
    }
    public Long getPhone() {
        return this.phone;
    }
    
    public void setPhone(Long phone) {
        this.phone = phone;
    }
    public Long getMobile() {
        return this.mobile;
    }
    
    public void setMobile(Long mobile) {
        this.mobile = mobile;
    }
    public String getBankname() {
        return this.bankname;
    }
    
    public void setBankname(String bankname) {
        this.bankname = bankname;
    }
    public Integer getAccountNo() {
        return this.accountNo;
    }
    
    public void setAccountNo(Integer accountNo) {
        this.accountNo = accountNo;
    }
    public String getBranchCode() {
        return this.branchCode;
    }
    
    public void setBranchCode(String branchCode) {
        this.branchCode = branchCode;
    }
    public String getAccholderName() {
        return this.accholderName;
    }
    
    public void setAccholderName(String accholderName) {
        this.accholderName = accholderName;
    }
    public Integer getApprove() {
        return this.approve;
    }
    
    public void setApprove(Integer approve) {
        this.approve = approve;
    }
    public BigDecimal getBalance() {
        return this.balance;
    }
    
    public void setBalance(BigDecimal balance) {
        this.balance = balance;
    }
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }
    public String getInfo() {
        return this.info;
    }
    
    public void setInfo(String info) {
        this.info = info;
    }




}


