package model;
// Generated Dec 29, 2011 5:10:49 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private String emailId;
     private String password;
     private long confirmCode;
     private String userType;
     private String status;
     private String userName;
     private Date date;
     private Set<Users> userses = new HashSet<Users>(0);
     private Set<UserAddress> userAddresses = new HashSet<UserAddress>(0);
     private Set<DeletedProduct> deletedProducts = new HashSet<DeletedProduct>(0);
     private Set<Stall> stalls = new HashSet<Stall>(0);
     private Set<Show> shows = new HashSet<Show>(0);
     private Set<Product> products = new HashSet<Product>(0);

    public User() {
    }

	
    public User(String emailId, String password, long confirmCode, String userType, String status, String userName, Date date) {
        this.emailId = emailId;
        this.password = password;
        this.confirmCode = confirmCode;
        this.userType = userType;
        this.status = status;
        this.userName = userName;
        this.date = date;
    }
    public User(String emailId, String password, long confirmCode, String userType, String status, String userName, Date date, Set<Users> userses, Set<UserAddress> userAddresses, Set<DeletedProduct> deletedProducts, Set<Stall> stalls, Set<Show> shows, Set<Product> products) {
       this.emailId = emailId;
       this.password = password;
       this.confirmCode = confirmCode;
       this.userType = userType;
       this.status = status;
       this.userName = userName;
       this.date = date;
       this.userses = userses;
       this.userAddresses = userAddresses;
       this.deletedProducts = deletedProducts;
       this.stalls = stalls;
       this.shows = shows;
       this.products = products;
    }
   
    public String getEmailId() {
        return this.emailId;
    }
    
    public void setEmailId(String emailId) {
        this.emailId = emailId;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public long getConfirmCode() {
        return this.confirmCode;
    }
    
    public void setConfirmCode(long confirmCode) {
        this.confirmCode = confirmCode;
    }
    public String getUserType() {
        return this.userType;
    }
    
    public void setUserType(String userType) {
        this.userType = userType;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public Set<Users> getUserses() {
        return this.userses;
    }
    
    public void setUserses(Set<Users> userses) {
        this.userses = userses;
    }
    public Set<UserAddress> getUserAddresses() {
        return this.userAddresses;
    }
    
    public void setUserAddresses(Set<UserAddress> userAddresses) {
        this.userAddresses = userAddresses;
    }
    public Set<DeletedProduct> getDeletedProducts() {
        return this.deletedProducts;
    }
    
    public void setDeletedProducts(Set<DeletedProduct> deletedProducts) {
        this.deletedProducts = deletedProducts;
    }
    public Set<Stall> getStalls() {
        return this.stalls;
    }
    
    public void setStalls(Set<Stall> stalls) {
        this.stalls = stalls;
    }
    public Set<Show> getShows() {
        return this.shows;
    }
    
    public void setShows(Set<Show> shows) {
        this.shows = shows;
    }
    public Set<Product> getProducts() {
        return this.products;
    }
    
    public void setProducts(Set<Product> products) {
        this.products = products;
    }




}


