package model;
// Generated Dec 29, 2011 5:10:49 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Visitor generated by hbm2java
 */
public class Visitor  implements java.io.Serializable {


     private Long visitorId;
     private String email;
     private String ip;
     private Date date;
     private Date timespent;
     private String info;
     private Set<Show> shows = new HashSet<Show>(0);
     private Set<Stall> stalls = new HashSet<Stall>(0);

    public Visitor() {
    }

	
    public Visitor(String ip, Date date) {
        this.ip = ip;
        this.date = date;
    }
    public Visitor(String email, String ip, Date date, Date timespent, String info, Set<Show> shows, Set<Stall> stalls) {
       this.email = email;
       this.ip = ip;
       this.date = date;
       this.timespent = timespent;
       this.info = info;
       this.shows = shows;
       this.stalls = stalls;
    }
   
    public Long getVisitorId() {
        return this.visitorId;
    }
    
    public void setVisitorId(Long visitorId) {
        this.visitorId = visitorId;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getIp() {
        return this.ip;
    }
    
    public void setIp(String ip) {
        this.ip = ip;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public Date getTimespent() {
        return this.timespent;
    }
    
    public void setTimespent(Date timespent) {
        this.timespent = timespent;
    }
    public String getInfo() {
        return this.info;
    }
    
    public void setInfo(String info) {
        this.info = info;
    }
    public Set<Show> getShows() {
        return this.shows;
    }
    
    public void setShows(Set<Show> shows) {
        this.shows = shows;
    }
    public Set<Stall> getStalls() {
        return this.stalls;
    }
    
    public void setStalls(Set<Stall> stalls) {
        this.stalls = stalls;
    }




}


